### ISSUE TITLE
Insert "loading gif" after hitting submit (on feedback win)

### ISSUE THREAD

**Issue by omarieclaire** [omarieclaire/common#100]
When a new player joins Common, there is a very long wait after the new player puts their username and email in to the form. There is currently no visual feedback, so the player tends to hit submit again and get "username taken" errors (there is no error, it's just a double submit).

One solution is to insert a "loading gif" after the player clicks submit. Or, at the least, text which says "checking database, very hard work, please wait"

**Comment by omarieclaire** [comment]
What happens when...On win

Player tries to take a taken username -> there is an error message
Player types in email wrong ->
Player types in taken username and correct email ->

**Comment by theophani** [comment]
Fixed! It looks kinda like this:

![screen shot 2018-06-02 at 00 19 11](https://user-images.githubusercontent.com/364246/40865825-b087daf2-65fa-11e8-8630-0970fd251ab0.png)
