### ISSUE TITLE
Icons should never overlap

### ISSUE THREAD

**Issue by omarieclaire** [omarieclaire/common#101]
Zoom icons and other icons should not overlap, even when people are using small devices in landscape mode. Is there a css way to prevent possible overlap?

**Comment by theophani** [comment]
There is! I'll look at this now.

**Comment by theophani** [comment]
Verified: this is not an issue anymore even on tiny phones:

![screen shot 2018-06-01 at 17 31 32](https://user-images.githubusercontent.com/364246/40849289-d3eaecfc-65c1-11e8-88a6-0cb9edd1c799.png)
