### ISSUE TITLE
SVG stuck in top corner when user is not logged in (and also when some users *are* signed in)

### ISSUE THREAD

**Issue by omarieclaire** [omarieclaire/common#104]
This is a new issue when we added the colored edges for the player. The issue is someone is calling `util.getNodeForEdges` with an `undefined` `node` param. This makes sense because of the user is not logged in, we don’t have a node for them.
The fix is to just heck if `node` is `undefined` before calling that filter in `commonplay`.js`

**Comment by omarieclaire** [comment]
Connor is experiencing the same problem even though he is signed in 
<img width="819" alt="screen shot 2018-06-01 at 12 09 12 pm" src="https://user-images.githubusercontent.com/8434943/40851207-9eb556e4-6594-11e8-84a7-f9422471a57f.png">

**Comment by theophani** [comment]
pretty sure Aaron's change fixes this
