### ISSUE TITLE
set default zoom on mobile to much further away

### ISSUE THREAD

**Issue by omarieclaire** [omarieclaire/common#111]
When I open commonplay.ca on mobile, it's a little overwhelming as it is extremely zoomed in.

The svg interferes visually with the console and zoom elements and my ability to zoom out is not immediately obvious. For this reason, seeing the common as a small element at first would be good.

**Comment by theophani** [comment]
Fixed here:
https://github.com/omarieclaire/common/commit/a6d3a57d1ed3d85ce0a17959eb6852f0b657d814

If you want adjust the size, or the rules, you can do that here:
https://github.com/omarieclaire/common/blob/master/public/js/commonplay.js#L455-L464
