### ISSUE TITLE
Common header "Common" overlaps on modals

### ISSUE THREAD

**Issue by omarieclaire** [omarieclaire/common#112]
Because the page title "Common" is at the very front, it overlaps on modal boxes on mobile. It would be good to either move the title "Common" back a level (visually) **or** to move the modals down a bit from the top of the page.

**Comment by theophani** [comment]
The issue is not that it is overlapping, but that the entire `#ui` element has `opacity: 0.7`

**Comment by theophani** [comment]
(I fixed it by moving down the modal)
