### ISSUE TITLE
Mobile zoom bug

### ISSUE THREAD

**Issue by omarieclaire** [omarieclaire/common#113]
When I zoomed in using my fingers on the graph (svg) on mobile (safari, iPhone) the page itself somehow zoomed and all the zoom buttons, settings etc disappeared out of view. I was unable to zoom out, until eventually I figured out how to pinch the whole page inwards.

**Comment by theophani** [comment]
This is a feature, not a big:

https://wouterdeschuyter.be/blog/how-to-disable-viewport-scaling-in-ios-10-you-dont
