### ISSUE TITLE
Hold-click (aka force click) unwanted behaviour

### ISSUE THREAD

**Issue by omarieclaire** [omarieclaire/common#114]
When I hold-click (click without immediate release) anywhere in the svg (click and hold) it highlights the "Common Life Force" text at the top of the network. We should disable this.

A hold-click (force click) should do nothing (or something, but probably not at this point)

**Comment by theophani** [comment]
I haven’t been able to replicate this.

**Comment by omarieclaire** [comment]
Ah I really should have written "mobile" issue on this. I thought I did. It came up in playtesting.

**Comment by theophani** [comment]
Ah, it looks like a feature of the annotation library

**Comment by omarieclaire** [comment]
An unfortunate feature!

**Comment by theophani** [comment]
Okay, this is definitely an iOS feature. It is trying to highlighting the word you are holding over. I'm looking to see if I can shut it off, though turning off the ability to select text is … questionable. Like, what if someone tries to select help text 🤔

**Comment by theophani** [comment]
FIIIIIIIXED:
https://github.com/omarieclaire/common/commit/2eb0564badfd89adcf6cdc19735bbfa5e426bc82
