### ISSUE TITLE
modals are too transparent -> hard to read text

### ISSUE THREAD

**Issue by omarieclaire** [omarieclaire/common#120]

**Comment by theophani** [comment]
I fixed this by moving all the modals out of the `#ui` div, so that they are not subject to the `opacity: 0.8` rule:

https://github.com/omarieclaire/common/commit/667c0c4ea449e1eb3719b2e602f2ae25566b9e33

If you think these are now too intense, then you can dial it down using:

```
#modals {
  opacity: 0.9;
}
```
