### ISSUE TITLE
Set up the settings menu and get settings working

### ISSUE THREAD

**Issue by omarieclaire** [omarieclaire/common#20]
In the settings menu (the modal) there should be a few checkboxes or toggle [on/off] boxes.

Sound effects (on/off) -on by default
Music (on/off) - on by default
Zoom Buttons (on/off) -off by default
High Contrast (on/off) -off by default
Larger Font (on/off) -off by default
OpenDyslexic (on/off) - off by default

**Comment by theophani** [comment]
@omarieclaire Does “Zoom Buttons off” mean hide the on screen zoom buttons?

**Comment by omarieclaire** [comment]
@theophani yes, exactly. For people with small screens who want them out of the way
