### ISSUE TITLE
Make a larger transparent node under the visible svg

### ISSUE THREAD

**Issue by omarieclaire** [omarieclaire/common#61]
People were struggling to click on the nodes when they are small. But large nodes look crowded. 

Can we make large totally transparent nodes, and draw the visible ones on top?

Steps
- Draw large nodes as transparent 
- Draw small coloured circle on top of each node 
- Each small coloured circle is banded by colored rings representing the health of the node.

**Comment by theophani** [comment]
i fixed this by adding a thick transparent border. I think that works!
